Hi tony. Hope you are well. Latest update syncs better but FCs frequently. Looks like an NPE in the widget. Joe
java.lang.RuntimeException: Unable to start receiver nz.gen.wellington.guardian.android.widgets.FavouriteStoriesWidget: java.lang.NullPointerException
at android.app.ActivityThread.handleReceiver(ActivityThread.java:2821)
at android.app.ActivityThread.access$3200(ActivityThread.java:125)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2083)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:123)
at android.app.ActivityThread.main(ActivityThread.java:4627)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:521)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:868)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at android.widget.RemoteViews$ReflectionAction.writeToParcel(RemoteViews.java:399)
at android.widget.RemoteViews.writeToParcel(RemoteViews.java:1003)
at com.android.internal.appwidget.IAppWidgetService$Stub$Proxy.updateAppWidgetIds(IAppWidgetService.java:374)
at android.appwidget.AppWidgetManager.updateAppWidget(AppWidgetManager.java:246)
at nz.gen.wellington.guardian.android.widgets.TopStoriesWidget.refresh(TopStoriesWidget.java:78)
at nz.gen.wellington.guardian.android.widgets.TopStoriesWidget.onUpdate(TopStoriesWidget.java:41)
at android.appwidget.AppWidgetProvider.onReceive(AppWidgetProvider.java:61)
at android.app.ActivityThread.handleReceiver(ActivityThread.java:2810)